### ISSUE TITLE
Testing result not same as shown in the paper

### ISSUE THREAD

**Issue by vincentme** [itanhe/DeepBBS#1]
Hi, thanks for sharing your code. 

I was trying to test the model. But the result is different from the number reported in the paper. Could you please indicate where did I miss? Thanks

The command I ran is `--n_subsampled_points 768 --DeepBBS_pp True --unseen True --model_path ./pretrained/unseen_categories.t7 --eval` with the downloaded weights. 
The result is 
`100%|██████████| 1266/1266 [03:02<00:00,  6.92it/s]==FINAL TEST==
Loss: 0.014110, rot_MSE: 4.875254, rot_RMSE: 2.207998, rot_MAE: 0.175070, trans_MSE: 0.000184, trans_RMSE: 0.013547, trans_MAE: 0.001740, rot_R2: 0.970580, trans_R2: 0.997783`

Besides, you mentioned supplementary material in the paper. Is it uploaded?

**Comment by itanhe** [comment]
Hi @vincentme,
Thank you for your interest in our paper. I found that the weights didn't match the published version of the code, and the code was not of the last version, so I updated both. Please **download the weights** again, and **pull the last commit**. Let me know if you still face inconsistency with the paper.

Regrading the supplementary material, we added it to Arxiv. It should appear there in a day or two.

**Comment by vincentme** [comment]
Thank you. Problem solved!
